# Site settings
title: Nayef Copty
email: nrcopty@gmail.com
description: "Nayef Copty's Website"
url: "http://www.nayefcopty.com"
github_username:  nayefc
linkedin_username: nayefc

# Build settings
markdown: kramdown

navigation:
  - title: /home
    url: /
  - title: /projects
    url: /projects/
  - title: /blog
    url: /blog/
